import numpy as np
a = np.arange(12).reshape(3, 4)
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
b = a.reshape(4, 3)
print(b)
c = a.reshape(12)
print(c)
d = a.reshape(4, -1)
print(d)
f = a.reshape(3, -1)
print(f)